#!/bin/bash
set -euo pipefail

# pick-colors.sh
# - Picks a random wallpaper.
# - Extracts a distinct color palette from it (requires ImageMagick).
# - Generates a Waybar style.css that is colorful and cohesive.
# - Applies the theme.

# --- Configuration ---
WALLPAPER_DIR="${HOME}/.config/source-of-truth/wallpapers"
OUT_DIR="${HOME}/.config/source-of-truth"
WAYBAR_CSS_DIR="${HOME}/.config/waybar"

# --- Helper Functions ---
hex_to_rgb() {
    local hex=${1#"#"}
    printf "%d,%d,%d" "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

# --- Main Script ---
mkdir -p "$OUT_DIR" "$WAYBAR_CSS_DIR"

# 1. Select a random wallpaper
WALLPAPER=$(find "$WALLPAPER_DIR" -type f \( -iname '*.jpg' -o -iname '*.png' \) -print0 | shuf -z -n1 | tr -d '\0')
if [[ -z "$WALLPAPER" ]]; then
    echo "Warning: No wallpapers found in $WALLPAPER_DIR. Using default colors." >&2
    WALLPAPER=""
fi

# 2. Extract a palette of distinct colors
if [[ -n "$WALLPAPER" ]] && command -v magick >/dev/null 2>&1; then
    palette_raw=$(magick "$WALLPAPER" +dither -colors 8 -unique-colors -scale 100x100\! txt:- | grep -oP '#[0-9a-fA-F]{6}' | awk '!seen[$0]++')
    palette=($palette_raw)
else
    palette=("#282a36" "#f8f8f2" "#50fa7b" "#ffb86c" "#ff79c6" "#bd93f9" "#8be9fd" "#ff5555")
fi


# Ensure we have enough colors, otherwise fallback to a default palette
if ((${#palette[@]} < 4)); then
    echo "Warning: Could not extract a diverse enough palette. Using defaults." >&2
    palette=("#282a36" "#f8f8f2" "#50fa7b" "#ffb86c" "#ff79c6" "#bd93f9" "#8be9fd" "#ff5555")
fi

# 3. Assign distinct colors for the theme
BG="${palette[0]}"
ACCENT1="${palette[1]}"
ACCENT2="${palette[2]}"
URGENT="${palette[3]}"
FG="#ffffff" # Default foreground, to be adjusted

# Helper function to find a good contrasting foreground color
find_contrast_fg() {
    local bg_hex=${1#"#"}
    local r_bg=$((16#${bg_hex:0:2}))
    local g_bg=$((16#${bg_hex:2:2}))
    local b_bg=$((16#${bg_hex:4:2}))
    local lum_bg=$(( (299*r_bg + 587*g_bg + 114*b_bg) / 1000 ))

    if (( lum_bg > 128 )); then
        FG="#000000"
    else
        FG="#ffffff"
    fi
}

find_contrast_fg "$BG"

# Convert main colors to RGB for rgba() CSS function
BG_RGB=$(hex_to_rgb "$BG")
ACCENT2_RGB=$(hex_to_rgb "$ACCENT2")

# 4. Generate the Waybar style.css
cat > "${WAYBAR_CSS_DIR}/style.css" << EOF
/* Generated by pick-colors.sh */

* {
    border: none;
    border-radius: 0;
    font-family: JetBrains Mono, monospace;
    font-size: 14px;
    min-height: 0;
}

window#waybar {
    background-color: rgba(${BG_RGB}, 0.7); /* Semi-transparent background */
    color: ${FG};
}

#workspaces button {
    padding: 0 5px;
    background-color: transparent;
    color: ${FG};
    border-radius: 8px 8px 0 0;
}

#workspaces button:hover {
    background: rgba(0, 0, 0, 0.2);
}

#workspaces button.focused {
    background-color: ${ACCENT1};
    color: #000000;
}

#workspaces button.urgent {
    background-color: ${URGENT};
}

.module {
    padding: 0 10px;
    margin: 0 4px;
    background-color: rgba(${ACCENT2_RGB}, 0.5); /* Semi-transparent accent */
    border-radius: 8px 8px 0 0;
}

#clock, #battery, #pulseaudio, #network, #custom-wp-button {
    padding: 0 10px;
}
EOF

# 5. Apply the theme
if command -v swww >/dev/null 2>&1; then
    swww img "$WALLPAPER" --transition-type any
fi
systemctl --user restart waybar.service

echo "Theme updated successfully!"
echo "Wallpaper: $WALLPAPER"
echo "BG: $BG, FG: $FG, ACCENT1: $ACCENT1, ACCENT2: $ACCENT2"
