#!/bin/bash
set -euo pipefail

# pick-colors.sh
# - Picks a random wallpaper.
# - Extracts a color palette from it (requires ImageMagick), or uses a default palette.
# - Generates a Waybar style.css that is compatible with its CSS parser.
# - Applies the theme.

# --- Configuration ---
WALLPAPER_DIR="${HOME}/.config/source-of-truth/wallpapers"
OUT_DIR="${HOME}/.config/source-of-truth"
WAYBAR_CSS_DIR="${HOME}/.config/waybar"

# --- Helper Functions ---
hex_to_rgb() {
    local hex=${1#"#"}
    printf "%d,%d,%d" "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

# --- Main Script ---
# Ensure required directories exist
mkdir -p "$OUT_DIR" "$WAYBAR_CSS_DIR"

# 1. Select a random wallpaper
WALLPAPER=$(find "$WALLPAPER_DIR" -type f \( -iname '*.jpg' -o -iname '*.png' \) -print0 | shuf -z -n1 | tr -d '\0')
if [[ -z "$WALLPAPER" ]]; then
    echo "Warning: No wallpapers found in $WALLPAPER_DIR. Using default colors." >&2
    WALLPAPER=""
fi

# 2. Extract colors using ImageMagick, with a fallback
if [[ -n "$WALLPAPER" ]] && command -v magick >/dev/null 2>&1; then
    palette_raw=$(magick "$WALLPAPER" +dither -colors 8 -unique-colors -scale 100x100\! txt:- | grep -oP '#[0-9a-fA-F]{6}')
    palette=($palette_raw)
else
    palette=("#282a36" "#f8f8f2" "#50fa7b" "#ffb86c" "#ff79c6" "#bd93f9" "#8be9fd" "#ff5555")
fi

# 3. Define the main theme colors from the palette
BG="${palette[0]}"
FG="#f8f8f2" # Default foreground
ACCENT1="${palette[2]}"
ACCENT2="${palette[3]}"
URGENT="${palette[7]}"

# Helper function to find a good contrasting foreground color
find_contrast_fg() {
    local bg_hex=${1#"#"}
    local r_bg=$((16#${bg_hex:0:2}))
    local g_bg=$((16#${bg_hex:2:2}))
    local b_bg=$((16#${bg_hex:4:2}))
    local lum_bg=$(( (299*r_bg + 587*g_bg + 114*b_bg) / 1000 ))

    if (( lum_bg > 128 )); then
        FG="#000000"
    else
        FG="#ffffff"
    fi
}

find_contrast_fg "$BG"

# Convert main colors to RGB for rgba() CSS function
BG_RGB=$(hex_to_rgb "$BG")
ACCENT2_RGB=$(hex_to_rgb "$ACCENT2")

MODULE_BG="rgba(${ACCENT_ACTIVE_RGB},${MODULE_BG_ALPHA})"
MODULE_HOVER_BG="rgba(${ACCENT_ACTIVE_RGB},${MODULE_HOVER_ALPHA})"
SUBTLE_RGB=$(hex_to_rgb "$SUBTLE")
SUBTLE_BG="rgba(${SUBTLE_RGB},${MODULE_BG_ALPHA})"

# choose bar overlay
BRIGHTNESS=$(brightness "$BG")
if [[ "$BRIGHTNESS" -lt 128 ]]; then
  BAR_OVERLAY="rgba(0,0,0,${BAR_OVERLAY_ALPHA_DARK})"
else
  BAR_OVERLAY="rgba(255,255,255,${BAR_OVERLAY_ALPHA_LIGHT})"
fi

# ---------- generate CSS ----------
cat > "$TMP_CSS" <<EOF
/* AUTO-GENERATED by pick-colors.sh - palette aware (rune theme) */
#waybar {
    background: ${BAR_OVERLAY};
    color: #${FG};
    font-family: "JetBrains Mono", monospace;
    font-size: 14px;
    padding: 6px 10px;
}

/* default color for all descendants */
#waybar, #waybar * {
    color: #${FG};
    background: transparent;
}

/* workspace container */
#custom-hypr-workspaces {
    padding-left: 6px;
    margin-right: 8px;
}

/* workspace child elements (JSON-mode) */
#custom-hypr-workspaces > .workspace {
    color: #${ACCENT2};
    background: rgba(${ACCENT_INACTIVE_RGB},0.14);
    padding: 4px 10px;
    border-radius: 10px;
    font-weight: 700;
    margin-right: 8px;
    border: none;
    letter-spacing: 0.6px;
}

/* focused workspace accent */
#custom-hypr-workspaces > .workspace.focused {
    color: #${BG};
    background-color: ${ACCENT_ACTIVE};
}

/* occupied but not focused */
#custom-hypr-workspaces > .workspace.occupied {
    background: rgba(${ACCENT_INACTIVE_RGB},0.22);
}

/* urgent */
#custom-hypr-workspaces > .workspace.urgent {
    color: #ffffff;
    background-color: rgba(200,60,60,0.95);
}

/* decorative runes (best-effort). If pseudo-elements are unsupported you will simply not see them. */
#custom-hypr-workspaces > .workspace::before {
    content: "᚛";
    margin-right: 6px;
    opacity: 0.9;
    color: #${SUBTLE};
}

/* focused rune variant */
#custom-hypr-workspaces > .workspace.focused::before {
    content: "᚜";
    color: #${HIGHLIGHT};
}

/* hover */
#custom-hypr-workspaces > .workspace:hover {
    color: #${BG};
    background-color: rgba(${ACCENT_ACTIVE_RGB},0.26);
}

#workspaces button:hover {
    background: rgba(0, 0, 0, 0.2);
}

#workspaces button.focused {
    background-color: ${ACCENT1};
    color: #000000;
}

#workspaces button.urgent {
    background-color: ${URGENT};
}

.module {
    padding: 0 10px;
    margin: 0 4px;
    background-color: rgba(${ACCENT2_RGB}, 0.5); /* Semi-transparent accent */
}

#clock, #battery, #pulseaudio, #network, #custom-wp-button {
    padding: 0 10px;
    background-color: rgba(${ACCENT2_RGB}, 0.5);
}
EOF

# 5. Apply the theme
if [[ -n "$WALLPAPER" ]] && command -v swww >/dev/null 2>&1; then
    swww img "$WALLPAPER" --transition-type any
fi
systemctl --user restart waybar.service

echo "Theme updated successfully!"
if [[ -n "$WALLPAPER" ]]; then
    echo "Wallpaper: $WALLPAPER"
fi
echo "BG: $BG, FG: $FG, ACCENT1: $ACCENT1, ACCENT2: $ACCENT2"
