#!/bin/bash
set -euo pipefail

# pick-colors.sh
# - Picks a random wallpaper.
# - Extracts a distinct color palette from it (requires ImageMagick).
# - Generates a Waybar style.css, qt6ct color scheme, and Hyprland color config.
# - Applies the theme.

# --- Configuration ---
WALLPAPER_DIR="${HOME}/.config/source-of-truth/wallpapers"
OUT_DIR="${HOME}/.config/source-of-truth"
WAYBAR_CSS_DIR="${HOME}/.config/waybar"
QT5CT_DIR="${HOME}/.config/qt5ct/colors"
QT6CT_DIR="${HOME}/.config/qt6ct/colors"
HYPRLAND_DIR="${HOME}/.config/hypr"
ROFI_DIR="${HOME}/.config/rofi"
KITTY_DIR="${HOME}/.config/kitty"

# --- Helper Functions ---
hex_to_rgb() {
    local hex=${1#"#"}
    printf "%d,%d,%d" "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

get_brightness() {
    local hex=${1#"#"}
    local r=$((16#${hex:0:2}))
    local g=$((16#${hex:2:2}))
    local b=$((16#${hex:4:2}))
    echo $(( (299*r + 587*g + 114*b) / 1000 ))
}


# --- Main Script ---
mkdir -p "$OUT_DIR" "$WAYBAR_CSS_DIR" "$QT5CT_DIR" "$QT6CT_DIR" "$HYPRLAND_DIR" "$ROFI_DIR" "$KITTY_DIR"

# 1. Select a random wallpaper
if [[ -d "$WALLPAPER_DIR" ]]; then
    WALLPAPER=$(find "$WALLPAPER_DIR" -type f \( -iname '*.jpg' -o -iname '*.png' \) -print0 | shuf -z -n1 | tr -d '\0')
else
    WALLPAPER=""
fi
if [[ -z "$WALLPAPER" ]]; then
    echo "Warning: No wallpapers found in $WALLPAPER_DIR. Using default colors." >&2
    WALLPAPER=""
fi

# 2. Extract a palette of distinct colors
if [[ -n "$WALLPAPER" ]] && command -v magick >/dev/null 2>&1; then
    palette_raw=$(magick "$WALLPAPER" +dither -colors 8 -unique-colors -scale 100x100\! txt:- | grep -oP '#[0-9a-fA-F]{6}' | awk '!seen[$0]++')
    palette=($palette_raw)
else
    palette=("#282a36" "#f8f8f2" "#50fa7b" "#ffb86c" "#ff79c6" "#bd93f9" "#8be9fd" "#ff5555")
fi


# Ensure we have enough colors, otherwise fallback to a default palette
if ((${#palette[@]} < 4)); then
    echo "Warning: Could not extract a diverse enough palette. Using defaults." >&2
    palette=("#282a36" "#f8f8f2" "#50fa7b" "#ffb86c" "#ff79c6" "#bd93f9" "#8be9fd" "#ff5555")
fi

# 3. Assign distinct colors for the theme
# Find the darkest and brightest colors for BG and FG
darkest_color="${palette[0]}"
brightest_color="${palette[0]}"
min_brightness=$(get_brightness "${palette[0]}")
max_brightness=$(get_brightness "${palette[0]}")

for color in "${palette[@]}"; do
    brightness=$(get_brightness "$color")
    if (( brightness < min_brightness )); then
        min_brightness=$brightness
        darkest_color=$color
    fi
    if (( brightness > max_brightness )); then
        max_brightness=$brightness
        brightest_color=$color
    fi
done

BG=$darkest_color
FG=$brightest_color

# Assign remaining colors to accents, avoiding BG and FG
remaining_colors=()
for color in "${palette[@]}"; do
    if [[ "$color" != "$BG" && "$color" != "$FG" ]]; then
        remaining_colors+=("$color")
    fi
done

ACCENT1="${remaining_colors[0]:-${palette[1]}}"
ACCENT2="${remaining_colors[1]:-${palette[2]}}"
URGENT="${remaining_colors[2]:-${palette[3]}}"

# Helper function to find a good contrasting foreground color
find_contrast_fg() {
    local bg_hex=${1#"#"}
    local r_bg=$((16#${bg_hex:0:2}))
    local g_bg=$((16#${bg_hex:2:2}))
    local b_bg=$((16#${bg_hex:4:2}))
    local lum_bg=$(( (299*r_bg + 587*g_bg + 114*b_bg) / 1000 ))

    if (( lum_bg > 128 )); then
        echo "#000000"
    else
        echo "#ffffff"
    fi
}

FOCUSED_FG=$(find_contrast_fg "$ACCENT1")


# Convert main colors to RGB for rgba() CSS function
ACCENT2_RGB=$(hex_to_rgb "$ACCENT2")
ROFI_BG_TRANSPARENT="argb:DB${BG#"#"}"

# 4. Generate the Waybar style.css
cat > "${WAYBAR_CSS_DIR}/style.css" << EOF
/* Generated by pick-colors.sh */

* {
    border: none;
    border-radius: 0;
    font-family: JetBrains Mono, monospace;
    font-size: 14px;
    min-height: 0;
}

window#waybar {
    background-color: transparent;
    color: ${FG};
}

#workspaces button {
    padding: 0 5px;
    background-color: transparent;
    color: ${FG};
    border-radius: 8px;
}

#workspaces button:hover {
    background: rgba(0, 0, 0, 0.2);
}

#workspaces button.focused {
    background-color: ${ACCENT1};
    color: ${FOCUSED_FG};
}

#workspaces button.urgent {
    background-color: ${URGENT};
}

.module {
    padding: 0 10px;
    margin: 0 4px;
    background-color: rgba(${ACCENT2_RGB}, 0.5); /* Semi-transparent accent */
    border-radius: 8px;
}

#clock, #battery, #pulseaudio, #network, #custom-wp-button {
    padding: 0 10px;
}
EOF

# 5. Generate the qt6ct color scheme
cat > "${QT6CT_DIR}/GeneratedTheme.conf" << EOF
[General]
background=${BG}
foreground=${FG}
base=${BG}
text=${FG}
button=${ACCENT2}
button_text=${FOCUSED_FG}
highlight=${ACCENT1}
highlight_text=${FOCUSED_FG}
link=${ACCENT1}
link_visited=${ACCENT1}
[Palette]
active_window=${ACCENT2}
inactive_window=${BG}
active_highlight=${ACCENT1}
inactive_highlight=${ACCENT2}
EOF

cp "${QT6CT_DIR}/GeneratedTheme.conf" "${QT5CT_DIR}/GeneratedTheme.conf"

# 6. Generate the Hyprland color scheme
cat > "${HYPRLAND_DIR}/colors.conf" << EOF
# Generated by pick-colors.sh
\$active_border = rgba(${ACCENT1#"#"}ff)
\$inactive_border = rgba(${ACCENT2#"#"}ff)
general {
    col.active_border = \$active_border
    col.inactive_border = \$inactive_border
}
EOF


# 7. Generate the Rofi theme.rasi
cat > "${ROFI_DIR}/theme.rasi" << EOF
/* Generated by pick-colors.sh */

* {
    transparent: rgba(0, 0, 0, 0);
}

window {
    width:      600px;
    border:     2px;
    border-color: ${ACCENT1};
    border-radius: 15px;
    background-color: ${ROFI_BG_TRANSPARENT};
    text-color: ${FG};
}

mainbox {
    children: [ inputbar, listview ];
    padding: 10px;
    background-color: @transparent;
}

listview {
    lines: 8;
    columns: 1;
    scrollbar: false;
    background-color: @transparent;
    text-color: ${FG};
}

element {
    padding: 8px;
    border-radius: 8px;
    background-color: @transparent;
    text-color: ${FG};
}

element-text {
    background-color: inherit;
    text-color:       inherit;
}

element.selected {
    background-color: ${ACCENT1};
    text-color: ${FOCUSED_FG};
}

inputbar {
    padding: 10px;
    margin-bottom: 10px;
    border-radius: 8px;
    background-color: ${ACCENT2};
    text-color: ${FG};
}

prompt {
    enabled:          true;
    background-color: inherit;
    text-color:       inherit;
}
EOF

# 8. Generate the Kitty theme.conf
cat > "${KITTY_DIR}/theme.conf" << EOF
# Generated by pick-colors.sh

foreground ${FG}
background ${BG}
cursor ${ACCENT1}
selection_foreground ${BG}
selection_background ${ACCENT1}

# Black
color0 ${BG}
color8 ${BG}

# Red
color1 ${URGENT}
color9 ${URGENT}

# Green
color2 ${palette[2]}
color10 ${palette[2]}

# Yellow
color3 ${palette[3]}
color11 ${palette[3]}

# Blue
color4 ${palette[5]}
color12 ${palette[5]}

# Magenta
color5 ${palette[4]}
color13 ${palette[4]}

# Cyan
color6 ${palette[6]}
color14 ${palette[6]}

# White
color7 ${FG}
color15 ${FG}
EOF

# 9. Automate Kitty config
if ! grep -q "include theme.conf" "${KITTY_DIR}/kitty.conf" 2>/dev/null; then
    echo "include theme.conf" >> "${KITTY_DIR}/kitty.conf"
fi

# 10. Apply the theme
if [[ -n "$WALLPAPER" ]] && command -v swww >/dev/null 2>&1; then
    swww img "$WALLPAPER" --transition-type any
fi
if command -v systemctl >/dev/null 2>&1; then
    systemctl --user restart waybar.service
fi
if command -v hyprctl >/dev/null 2>&1; then
    hyprctl reload
fi

echo "Theme updated successfully!"
echo "Wallpaper: $WALLPAPER"
echo "BG: $BG, FG: $FG, ACCENT1: $ACCENT1, ACCENT2: $ACCENT2"
